version: '3'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "127.0.0.1:${WP_PORT:-8763}:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WP_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX:-wp_}
      - WORDPRESS_AUTO_UPDATE_CORE=false
      - WORDPRESS_CONFIG_EXTRA=define('DISALLOW_FILE_EDIT', true); define('DISALLOW_FILE_MODS', true);
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - wordpress_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
  db:
    image: mariadb:10.6
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${WP_DB_NAME:-wordpress}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
    networks:
      - wordpress_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
networks:
  wordpress_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
volumes:
  wordpress_data:
  db_data:
