
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "127.0.0.1:${WP_PORT:-8763}:80"
    user: 33:33
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WP_DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WP_TABLE_PREFIX:-wp_}
    
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    command: >
      bash -c "chown -R www-data:www-data /var/www/html && apache2-foreground" 

  db:
    image: mariadb:10.6
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${WP_DB_NAME:-wordpress}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
volumes:
  wordpress_data:
  db_data:
